/** Declaration file generated by dts-gen */

// export function binaryTransfer(integer: number, binary: number): string;

// export function bitwise(str: string): number;

// export function random(_len: number): string;

export function unique(text: string): string;


